spring:
  application:
#    this name should be the same that the prefix file that exists in the configurations, not the config server
    name: jp-config
  profiles:
    active: prod
  config:
#    this is the configuration server url
    import: optional:configserver:http://localhost:8888/
server:
  port: 8082


logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      #      used for tracing
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
